import { useStore } from './store'

export const languages = [
  { code: 'en', name: 'English' },
  { code: 'es', name: 'Español' },
  { code: 'fr', name: 'Français' },
  { code: 'pt', name: 'Português' },
  { code: 'de', name: 'Deutsch' },
  { code: 'ja', name: '日本語' },
  { code: 'zh', name: '中文' },
  { code: 'ar', name: 'العربية' },
  { code: 'hi', name: 'हिन्दी' },
  { code: 'it', name: 'Italiano' },
  { code: 'ru', name: 'Русский' },
  { code: 'ko', name: '한국어' },
]

// Machine-translated by an LLM, not a professional localization service —
// good enough to make language switching genuinely useful, but worth a
// native speaker's review before fully trusting it in production.
//
// Keys are the exact English source string (what every call site passes to
// t()). Dynamic strings use {placeholder} tokens filled in via t(key,
// params) — see interpolate() below. Missing languages/keys fall back to
// the English source.
const dict = {
  // --- nav / shared (pre-existing) ------------------------------------
  Discover: { es: 'Descubrir', fr: 'Découvrir', pt: 'Descobrir', de: 'Entdecken', ja: '発見', zh: '发现', ar: 'اكتشف', hi: 'खोजें', it: 'Scopri', ru: 'Обзор', ko: '발견' },
  Search: { es: 'Buscar', fr: 'Rechercher', pt: 'Pesquisar', de: 'Suchen', ja: '検索', zh: '搜索', ar: 'بحث', hi: 'खोजें', it: 'Cerca', ru: 'Поиск', ko: '검색' },
  Groups: { es: 'Grupos', fr: 'Groupes', pt: 'Grupos', de: 'Gruppen', ja: 'グループ', zh: '群组', ar: 'مجموعات', hi: 'समूह', it: 'Gruppi', ru: 'Группы', ko: '그룹' },
  Messages: { es: 'Mensajes', fr: 'Messages', pt: 'Mensagens', de: 'Nachrichten', ja: 'メッセージ', zh: '消息', ar: 'الرسائل', hi: 'संदेश', it: 'Messaggi', ru: 'Сообщения', ko: '메시지' },
  Profile: { es: 'Perfil', fr: 'Profil', pt: 'Perfil', de: 'Profil', ja: 'プロフィール', zh: '个人资料', ar: 'الملف الشخصي', hi: 'प्रोफ़ाइल', it: 'Profilo', ru: 'Профиль', ko: '프로필' },
  'View profile': { es: 'Ver perfil', fr: 'Voir le profil', pt: 'Ver perfil', de: 'Profil ansehen', ja: 'プロフィールを見る', zh: '查看资料', ar: 'عرض الملف الشخصي', hi: 'प्रोफ़ाइल देखें', it: 'Vedi profilo', ru: 'Просмотреть профиль', ko: '프로필 보기' },
  Settings: { es: 'Configuración', fr: 'Paramètres', pt: 'Configurações', de: 'Einstellungen', ja: '設定', zh: '设置', ar: 'الإعدادات', hi: 'सेटिंग्स', it: 'Impostazioni', ru: 'Настройки', ko: '설정' },
  Account: { es: 'Cuenta', fr: 'Compte', pt: 'Conta', de: 'Konto', ja: 'アカウント', zh: '账户', ar: 'الحساب', hi: 'खाता', it: 'Account', ru: 'Аккаунт', ko: '계정' },
  'Change password': { es: 'Cambiar contraseña', fr: 'Changer le mot de passe', pt: 'Alterar senha', de: 'Passwort ändern', ja: 'パスワードを変更', zh: '更改密码', ar: 'تغيير كلمة المرور', hi: 'पासवर्ड बदलें', it: 'Cambia password', ru: 'Изменить пароль', ko: '비밀번호 변경' },
  'Ad preferences': { es: 'Preferencias de anuncios', fr: 'Préférences publicitaires', pt: 'Preferências de anúncios', de: 'Anzeigeneinstellungen', ja: '広告設定', zh: '广告偏好设置', ar: 'تفضيلات الإعلانات', hi: 'विज्ञापन प्राथमिकताएं', it: 'Preferenze annunci', ru: 'Настройки рекламы', ko: '광고 환경설정' },
  Billing: { es: 'Facturación', fr: 'Facturation', pt: 'Faturamento', de: 'Abrechnung', ja: '請求', zh: '账单', ar: 'الفواتير', hi: 'बिलिंग', it: 'Fatturazione', ru: 'Оплата', ko: '결제' },
  Archive: { es: 'Archivo', fr: 'Archive', pt: 'Arquivo', de: 'Archiv', ja: 'アーカイブ', zh: '存档', ar: 'الأرشيف', hi: 'संग्रह', it: 'Archivio', ru: 'Архив', ko: '보관함' },
  Notifications: { es: 'Notificaciones', fr: 'Notifications', pt: 'Notificações', de: 'Benachrichtigungen', ja: '通知', zh: '通知', ar: 'الإشعارات', hi: 'सूचनाएं', it: 'Notifiche', ru: 'Уведомления', ko: '알림' },
  'Account privacy': { es: 'Privacidad de la cuenta', fr: 'Confidentialité du compte', pt: 'Privacidade da conta', de: 'Kontoprivatsphäre', ja: 'アカウントのプライバシー', zh: '账户隐私', ar: 'خصوصية الحساب', hi: 'खाता गोपनीयता', it: 'Privacy account', ru: 'Конфиденциальность аккаунта', ko: '계정 개인정보' },
  'Blocked & reported': { es: 'Bloqueados y reportados', fr: 'Bloqués et signalés', pt: 'Bloqueados e denunciados', de: 'Blockiert & gemeldet', ja: 'ブロックと報告', zh: '已屏蔽和举报', ar: 'المحظورون والمُبلَّغ عنهم', hi: 'ब्लॉक और रिपोर्ट किए गए', it: 'Bloccati e segnalati', ru: 'Заблокированные и жалобы', ko: '차단 및 신고' },
  'Device permissions': { es: 'Permisos del dispositivo', fr: 'Autorisations de l’appareil', pt: 'Permissões do dispositivo', de: 'Geräteberechtigungen', ja: 'デバイスの権限', zh: '设备权限', ar: 'أذونات الجهاز', hi: 'डिवाइस अनुमतियां', it: 'Permessi dispositivo', ru: 'Разрешения устройства', ko: '기기 권한' },
  Language: { es: 'Idioma', fr: 'Langue', pt: 'Idioma', de: 'Sprache', ja: '言語', zh: '语言', ar: 'اللغة', hi: 'भाषा', it: 'Lingua', ru: 'Язык', ko: '언어' },
  Plan: { es: 'Plan', fr: 'Forfait', pt: 'Plano', de: 'Tarif', ja: 'プラン', zh: '套餐', ar: 'الخطة', hi: 'योजना', it: 'Piano', ru: 'Тариф', ko: '요금제' },
  'Safety & privacy': { es: 'Seguridad y privacidad', fr: 'Sécurité et confidentialité', pt: 'Segurança e privacidade', de: 'Sicherheit & Datenschutz', ja: '安全とプライバシー', zh: '安全与隐私', ar: 'السلامة والخصوصية', hi: 'सुरक्षा और गोपनीयता', it: 'Sicurezza e privacy', ru: 'Безопасность и конфиденциальность', ko: '안전 및 개인정보' },
  'Sign out': { es: 'Cerrar sesión', fr: 'Se déconnecter', pt: 'Sair', de: 'Abmelden', ja: 'ログアウト', zh: '退出登录', ar: 'تسجيل الخروج', hi: 'साइन आउट', it: 'Esci', ru: 'Выйти', ko: '로그아웃' },
  Save: { es: 'Guardar', fr: 'Enregistrer', pt: 'Salvar', de: 'Speichern', ja: '保存', zh: '保存', ar: 'حفظ', hi: 'सहेजें', it: 'Salva', ru: 'Сохранить', ko: '저장' },
  Cancel: { es: 'Cancelar', fr: 'Annuler', pt: 'Cancelar', de: 'Abbrechen', ja: 'キャンセル', zh: '取消', ar: 'إلغاء', hi: 'रद्द करें', it: 'Annulla', ru: 'Отмена', ko: '취소' },
  Back: { es: 'Atrás', fr: 'Retour', pt: 'Voltar', de: 'Zurück', ja: '戻る', zh: '返回', ar: 'رجوع', hi: 'वापस', it: 'Indietro', ru: 'Назад', ko: '뒤로' },

  // --- Discover ---------------------------------------------------------
  'Confirming your payment…': { es: 'Confirmando tu pago…', fr: 'Confirmation de votre paiement…', pt: 'Confirmando seu pagamento…', de: 'Zahlung wird bestätigt…', ja: 'お支払いを確認中…', zh: '正在确认付款…', ar: 'جارٍ تأكيد الدفع…', hi: 'आपका भुगतान पुष्टि हो रहा है…', it: 'Conferma del pagamento…', ru: 'Подтверждение платежа…', ko: '결제 확인 중…' },
  'Your trip has ended': { es: 'Tu viaje ha terminado', fr: 'Votre voyage est terminé', pt: 'Sua viagem terminou', de: 'Deine Reise ist beendet', ja: '旅行が終了しました', zh: '您的旅程已结束', ar: 'انتهت رحلتك', hi: 'आपकी यात्रा समाप्त हो गई है', it: 'Il tuo viaggio è terminato', ru: 'Ваша поездка завершена', ko: '여행이 종료되었습니다' },
  'Trip passes cover up to 14 days. Renew your plan to browse and match with travelers again.': { es: 'Los pases de viaje cubren hasta 14 días. Renueva tu plan para explorar y conectar con viajeros de nuevo.', fr: 'Les pass voyage couvrent jusqu’à 14 jours. Renouvelez votre forfait pour parcourir et matcher à nouveau avec des voyageurs.', pt: 'Os passes de viagem cobrem até 14 dias. Renove seu plano para navegar e combinar com viajantes novamente.', de: 'Reisepässe gelten für bis zu 14 Tage. Erneuere deinen Tarif, um wieder Reisende zu durchsuchen und zu matchen.', ja: 'トリップパスは最大14日間有効です。プランを更新して、旅行者の閲覧とマッチを再開しましょう。', zh: '旅行通行证最多可使用14天。续订套餐以重新浏览并匹配旅行者。', ar: 'تغطي تذاكر الرحلات حتى 14 يومًا. جدد خطتك لتصفح المسافرين والتوافق معهم مرة أخرى.', hi: 'ट्रिप पास 14 दिनों तक मान्य हैं। यात्रियों को फिर से ब्राउज़ और मैच करने के लिए अपनी योजना नवीनीकृत करें।', it: 'I pass viaggio coprono fino a 14 giorni. Rinnova il tuo piano per sfogliare e trovare nuovi abbinamenti con i viaggiatori.', ru: 'Тревел-пропуск действует до 14 дней. Продлите тариф, чтобы снова просматривать путешественников и находить совпадения.', ko: '트립 패스는 최대 14일간 이용 가능합니다. 요금제를 갱신하여 다시 여행자를 둘러보고 매칭하세요.' },
  'Discover is for paying travelers': { es: 'Descubrir es para viajeros con plan de pago', fr: 'Découvrir est réservé aux voyageurs abonnés', pt: 'Descobrir é para viajantes pagantes', de: 'Entdecken ist für zahlende Reisende', ja: '「発見」は有料プランの旅行者向けです', zh: '“发现”功能仅限付费旅行者使用', ar: 'ميزة الاكتشاف مخصصة للمسافرين المشتركين', hi: 'खोजें सुविधा भुगतान करने वाले यात्रियों के लिए है', it: 'Scopri è riservato ai viaggiatori con piano attivo', ru: 'Раздел «Обзор» доступен только платным путешественникам', ko: '발견 기능은 유료 요금제 이용자를 위한 기능입니다' },
  'Add a Trip Pass or subscription to browse and match with travelers of your nationality.': { es: 'Añade un pase de viaje o una suscripción para explorar y conectar con viajeros de tu nacionalidad.', fr: 'Ajoutez un pass voyage ou un abonnement pour parcourir et matcher avec des voyageurs de votre nationalité.', pt: 'Adicione um passe de viagem ou assinatura para navegar e combinar com viajantes da sua nacionalidade.', de: 'Füge einen Reisepass oder ein Abo hinzu, um Reisende deiner Nationalität zu durchsuchen und zu matchen.', ja: 'トリップパスまたはサブスクリプションを追加して、同じ国籍の旅行者を閲覧・マッチしましょう。', zh: '添加旅行通行证或订阅，即可浏览并匹配与您同国籍的旅行者。', ar: 'أضف تذكرة رحلة أو اشتراكًا لتصفح المسافرين من جنسيتك والتوافق معهم.', hi: 'अपनी राष्ट्रीयता के यात्रियों को ब्राउज़ और मैच करने के लिए ट्रिप पास या सदस्यता जोड़ें।', it: 'Aggiungi un pass viaggio o un abbonamento per sfogliare e trovare abbinamenti con viaggiatori della tua nazionalità.', ru: 'Добавьте тревел-пропуск или подписку, чтобы просматривать и находить совпадения с путешественниками вашей национальности.', ko: '같은 국적의 여행자를 둘러보고 매칭하려면 트립 패스 또는 구독을 추가하세요.' },
  'Add a plan to unlock': { es: 'Añade un plan para desbloquear', fr: 'Ajoutez un forfait pour débloquer', pt: 'Adicione um plano para desbloquear', de: 'Füge einen Tarif hinzu, um freizuschalten', ja: 'プランを追加してロック解除', zh: '添加套餐以解锁', ar: 'أضف خطة لإلغاء القفل', hi: 'अनलॉक करने के लिए एक योजना जोड़ें', it: 'Aggiungi un piano per sbloccare', ru: 'Добавьте тариф, чтобы разблокировать', ko: '잠금 해제를 위해 요금제 추가' },
  'Renew to unlock': { es: 'Renueva para desbloquear', fr: 'Renouvelez pour débloquer', pt: 'Renove para desbloquear', de: 'Erneuern zum Freischalten', ja: '更新してロック解除', zh: '续订以解锁', ar: 'جدد لإلغاء القفل', hi: 'अनलॉक करने के लिए नवीनीकृत करें', it: 'Rinnova per sbloccare', ru: 'Продлите, чтобы разблокировать', ko: '갱신하여 잠금 해제' },
  "You're out of swipes for this week": { es: 'Se te acabaron los deslizamientos de esta semana', fr: 'Vous n’avez plus de swipes cette semaine', pt: 'Você ficou sem deslizes esta semana', de: 'Du hast für diese Woche keine Swipes mehr', ja: '今週のスワイプ回数を使い切りました', zh: '本周滑动次数已用完', ar: 'لقد استنفدت عمليات السحب لهذا الأسبوع', hi: 'इस सप्ताह के लिए आपके स्वाइप समाप्त हो गए हैं', it: 'Hai esaurito gli swipe per questa settimana', ru: 'На этой неделе у вас закончились свайпы', ko: '이번 주 스와이프를 모두 사용했습니다' },
  'Travelers of your nationality, nearby right now.': { es: 'Viajeros de tu nacionalidad, cerca ahora mismo.', fr: 'Des voyageurs de votre nationalité, à proximité en ce moment.', pt: 'Viajantes da sua nacionalidade, por perto agora.', de: 'Reisende deiner Nationalität, gerade in deiner Nähe.', ja: '今、近くにいる同じ国籍の旅行者。', zh: '与您同国籍的旅行者，此刻就在附近。', ar: 'مسافرون من جنسيتك، بالقرب منك الآن.', hi: 'आपकी राष्ट्रीयता के यात्री, अभी आस-पास।', it: 'Viaggiatori della tua nazionalità, nelle vicinanze in questo momento.', ru: 'Путешественники вашей национальности рядом с вами прямо сейчас.', ko: '지금 근처에 있는 같은 국적의 여행자들.' },
  'Review skipped travelers': { es: 'Revisar viajeros omitidos', fr: 'Revoir les voyageurs ignorés', pt: 'Revisar viajantes ignorados', de: 'Übersprungene Reisende ansehen', ja: 'スキップした旅行者を確認', zh: '查看已跳过的旅行者', ar: 'مراجعة المسافرين المتجاوَزين', hi: 'छोड़े गए यात्रियों की समीक्षा करें', it: 'Rivedi i viaggiatori saltati', ru: 'Просмотреть пропущенных путешественников', ko: '건너뛴 여행자 다시 보기' },
  "Bring back people you've skipped": { es: 'Recupera a las personas que has omitido', fr: 'Faites revenir les personnes que vous avez ignorées', pt: 'Traga de volta pessoas que você ignorou', de: 'Hole übersprungene Personen zurück', ja: 'スキップした人を呼び戻す', zh: '找回您跳过的人', ar: 'أعد إظهار الأشخاص الذين تجاوزتهم', hi: 'आपके द्वारा छोड़े गए लोगों को वापस लाएं', it: 'Recupera le persone che hai saltato', ru: 'Вернуть пропущенных людей', ko: '건너뛴 사람 다시 보기' },
  "You're all caught up": { es: 'Estás al día', fr: 'Vous êtes à jour', pt: 'Você está em dia', de: 'Du bist auf dem neuesten Stand', ja: 'すべて確認済みです', zh: '您已浏览全部内容', ar: 'لقد اطّلعت على كل شيء', hi: 'आप सभी को देख चुके हैं', it: 'Sei aggiornato', ru: 'Вы всё просмотрели', ko: '모두 확인했습니다' },
  'Check back soon for more travelers nearby.': { es: 'Vuelve pronto para ver más viajeros cerca.', fr: 'Revenez bientôt pour voir plus de voyageurs à proximité.', pt: 'Volte em breve para ver mais viajantes por perto.', de: 'Schau bald wieder vorbei für weitere Reisende in der Nähe.', ja: '近くの旅行者が増えたらまた確認してください。', zh: '请稍后查看附近的更多旅行者。', ar: 'عد قريبًا للاطلاع على مزيد من المسافرين القريبين.', hi: 'आस-पास और यात्रियों के लिए जल्द फिर देखें।', it: 'Torna presto per altri viaggiatori nelle vicinanze.', ru: 'Загляните позже — рядом появятся новые путешественники.', ko: '곧 다시 확인해 주세요. 근처에 더 많은 여행자가 나타날 거예요.' },
  'From: {country}': { es: 'De: {country}', fr: 'De : {country}', pt: 'De: {country}', de: 'Aus: {country}', ja: '出身：{country}', zh: '来自：{country}', ar: 'من: {country}', hi: 'से: {country}', it: 'Da: {country}', ru: 'Из: {country}', ko: '출신: {country}' },
  'From: {home}  Visiting: {visiting}': { es: 'De: {home}  Visitando: {visiting}', fr: 'De : {home}  En visite : {visiting}', pt: 'De: {home}  Visitando: {visiting}', de: 'Aus: {home}  Zu Besuch in: {visiting}', ja: '出身：{home}　訪問中：{visiting}', zh: '来自：{home}　当前访问：{visiting}', ar: 'من: {home}  يزور الآن: {visiting}', hi: 'से: {home}  भ्रमण पर: {visiting}', it: 'Da: {home}  In visita a: {visiting}', ru: 'Из: {home}  Сейчас в поездке: {visiting}', ko: '출신: {home}  방문 중: {visiting}' },
  '{km} km away': { es: 'a {km} km', fr: 'à {km} km', pt: 'a {km} km', de: '{km} km entfernt', ja: '{km}km離れています', zh: '{km}公里外', ar: 'على بعد {km} كم', hi: '{km} किमी दूर', it: 'a {km} km', ru: 'в {km} км', ko: '{km}km 거리' },
  Undo: { es: 'Deshacer', fr: 'Annuler', pt: 'Desfazer', de: 'Rückgängig', ja: '元に戻す', zh: '撤销', ar: 'تراجع', hi: 'पूर्ववत करें', it: 'Annulla', ru: 'Отменить', ko: '실행 취소' },
  'Free access is capped at {limit} swipes a week. It resets on a rolling basis, or add a plan for unlimited swiping.': { es: 'El acceso gratuito está limitado a {limit} deslizamientos por semana. Se reinicia de forma continua, o añade un plan para deslizar sin límites.', fr: 'L’accès gratuit est limité à {limit} swipes par semaine. Il se réinitialise en continu, ou ajoutez un forfait pour des swipes illimités.', pt: 'O acesso gratuito é limitado a {limit} deslizes por semana. Ele se renova continuamente, ou adicione um plano para deslizar sem limites.', de: 'Der kostenlose Zugang ist auf {limit} Swipes pro Woche begrenzt. Das Limit läuft fortlaufend ab, oder füge einen Tarif für unbegrenztes Swipen hinzu.', ja: '無料プランは週{limit}回のスワイプに制限されています。制限はローリングでリセットされます。無制限にスワイプするにはプランを追加してください。', zh: '免费用户每周限{limit}次滑动，额度会持续滚动重置，或添加套餐以无限滑动。', ar: 'يقتصر الوصول المجاني على {limit} عملية سحب أسبوعيًا، ويُعاد تعيينها بشكل متجدد، أو أضف خطة للسحب غير المحدود.', hi: 'निःशुल्क एक्सेस प्रति सप्ताह {limit} स्वाइप तक सीमित है। यह रोलिंग आधार पर रीसेट होता है, या असीमित स्वाइप के लिए योजना जोड़ें।', it: "L'accesso gratuito è limitato a {limit} swipe a settimana. Si azzera in modo continuo, oppure aggiungi un piano per swipe illimitati.", ru: 'Бесплатный доступ ограничен {limit} свайпами в неделю. Лимит обновляется постоянно, либо добавьте тариф для безлимитных свайпов.', ko: '무료 이용은 주당 {limit}회 스와이프로 제한됩니다. 제한은 롤링 방식으로 초기화되며, 무제한 스와이프를 원하시면 요금제를 추가하세요.' },

  // --- Match modal --------------------------------------------------
  "It's a match": { es: 'Es un match', fr: "C'est un match", pt: 'Deu match', de: 'Es ist ein Match', ja: 'マッチしました', zh: '配对成功', ar: 'لقد تطابقتما', hi: 'यह एक मैच है', it: 'È un match', ru: 'Это совпадение!', ko: '매칭되었습니다' },
  'Send a message': { es: 'Enviar un mensaje', fr: 'Envoyer un message', pt: 'Enviar uma mensagem', de: 'Nachricht senden', ja: 'メッセージを送る', zh: '发送消息', ar: 'أرسل رسالة', hi: 'संदेश भेजें', it: 'Invia un messaggio', ru: 'Отправить сообщение', ko: '메시지 보내기' },
  'Keep browsing': { es: 'Seguir explorando', fr: 'Continuer à parcourir', pt: 'Continuar navegando', de: 'Weiter durchsuchen', ja: '引き続き閲覧する', zh: '继续浏览', ar: 'متابعة التصفح', hi: 'ब्राउज़ करना जारी रखें', it: 'Continua a sfogliare', ru: 'Продолжить просмотр', ko: '계속 둘러보기' },
  'You and {name} matched': { es: 'Tú y {name} hicieron match', fr: 'Vous et {name} avez matché', pt: 'Você e {name} deram match', de: 'Du und {name} haben ein Match', ja: 'あなたと{name}さんがマッチしました', zh: '您和{name}配对成功', ar: 'أنت و{name} تطابقتما', hi: 'आप और {name} मैच हो गए', it: 'Tu e {name} avete fatto match', ru: 'Вы и {name} — совпадение', ko: '나와 {name}님이 매칭되었습니다' },
  "Say hello, they're {distance} km away right now.": { es: 'Saluda, están a {distance} km de distancia ahora mismo.', fr: 'Dites bonjour, cette personne est à {distance} km en ce moment.', pt: 'Diga oi, essa pessoa está a {distance} km de distância agora.', de: 'Sag hallo, die Person ist gerade {distance} km entfernt.', ja: '挨拶しましょう。現在{distance}km離れた場所にいます。', zh: '打个招呼吧，对方现在距离您{distance}公里。', ar: 'قل مرحبًا، إنهم على بعد {distance} كم الآن.', hi: 'नमस्ते कहें, वे अभी {distance} किमी दूर हैं।', it: 'Saluta, si trova a {distance} km da te in questo momento.', ru: 'Поздоровайтесь — сейчас этот человек в {distance} км от вас.', ko: '인사해 보세요. 지금 {distance}km 떨어진 곳에 있어요.' },

  // --- Swipe card -----------------------------------------------------
  Like: { es: 'Me gusta', fr: "J'aime", pt: 'Curtir', de: 'Gefällt mir', ja: 'いいね', zh: '喜欢', ar: 'إعجاب', hi: 'पसंद', it: 'Mi piace', ru: 'Нравится', ko: '좋아요' },
  Pass: { es: 'Pasar', fr: 'Passer', pt: 'Pular', de: 'Überspringen', ja: 'パス', zh: '跳过', ar: 'تجاوز', hi: 'छोड़ें', it: 'Salta', ru: 'Пропустить', ko: '패스' },

  // --- Groups -----------------------------------------------------------
  'Group details are locked': { es: 'Los detalles del grupo están bloqueados', fr: 'Les détails du groupe sont verrouillés', pt: 'Os detalhes do grupo estão bloqueados', de: 'Gruppendetails sind gesperrt', ja: 'グループ詳細はロックされています', zh: '群组详情已锁定', ar: 'تفاصيل المجموعة مقفلة', hi: 'समूह विवरण लॉक है', it: 'I dettagli del gruppo sono bloccati', ru: 'Сведения о группе заблокированы', ko: '그룹 세부정보가 잠겨 있습니다' },
  'Trip passes cover up to 14 days. Renew your plan to see group meetups and locations again.': { es: 'Los pases de viaje cubren hasta 14 días. Renueva tu plan para volver a ver quedadas y ubicaciones de grupos.', fr: 'Les pass voyage couvrent jusqu’à 14 jours. Renouvelez votre forfait pour revoir les rencontres de groupe et leurs lieux.', pt: 'Os passes de viagem cobrem até 14 dias. Renove seu plano para ver encontros de grupo e locais novamente.', de: 'Reisepässe gelten für bis zu 14 Tage. Erneuere deinen Tarif, um Gruppentreffen und Orte wieder zu sehen.', ja: 'トリップパスは最大14日間有効です。プランを更新してグループの集まりや場所を再度確認しましょう。', zh: '旅行通行证最多可使用14天。续订套餐以重新查看群组聚会和地点。', ar: 'تغطي تذاكر الرحلات حتى 14 يومًا. جدد خطتك لرؤية تجمعات المجموعات ومواقعها مرة أخرى.', hi: 'ट्रिप पास 14 दिनों तक मान्य हैं। समूह मीटअप और स्थान फिर से देखने के लिए अपनी योजना नवीनीकृत करें।', it: 'I pass viaggio coprono fino a 14 giorni. Rinnova il tuo piano per rivedere gli incontri di gruppo e le località.', ru: 'Тревел-пропуск действует до 14 дней. Продлите тариф, чтобы снова видеть групповые встречи и места.', ko: '트립 패스는 최대 14일간 이용 가능합니다. 그룹 모임과 장소를 다시 보려면 요금제를 갱신하세요.' },
  'Groups are for paying travelers': { es: 'Los grupos son para viajeros con plan de pago', fr: 'Les groupes sont réservés aux voyageurs abonnés', pt: 'Grupos são para viajantes pagantes', de: 'Gruppen sind für zahlende Reisende', ja: '「グループ」は有料プランの旅行者向けです', zh: '“群组”功能仅限付费旅行者使用', ar: 'المجموعات مخصصة للمسافرين المشتركين', hi: 'समूह भुगतान करने वाले यात्रियों के लिए हैं', it: 'I gruppi sono riservati ai viaggiatori con piano attivo', ru: 'Группы доступны только платным путешественникам', ko: '그룹 기능은 유료 요금제 이용자를 위한 기능입니다' },
  'Add a Trip Pass or subscription to browse, join, and create group meetups.': { es: 'Añade un pase de viaje o suscripción para explorar, unirte y crear quedadas de grupo.', fr: 'Ajoutez un pass voyage ou un abonnement pour parcourir, rejoindre et créer des rencontres de groupe.', pt: 'Adicione um passe de viagem ou assinatura para navegar, entrar e criar encontros de grupo.', de: 'Füge einen Reisepass oder ein Abo hinzu, um Gruppentreffen zu durchsuchen, beizutreten und zu erstellen.', ja: 'トリップパスまたはサブスクリプションを追加して、グループの集まりを閲覧・参加・作成しましょう。', zh: '添加旅行通行证或订阅，即可浏览、加入并创建群组聚会。', ar: 'أضف تذكرة رحلة أو اشتراكًا لتصفح تجمعات المجموعات والانضمام إليها وإنشائها.', hi: 'समूह मीटअप ब्राउज़ करने, शामिल होने और बनाने के लिए ट्रिप पास या सदस्यता जोड़ें।', it: 'Aggiungi un pass viaggio o un abbonamento per sfogliare, unirti e creare incontri di gruppo.', ru: 'Добавьте тревел-пропуск или подписку, чтобы просматривать, присоединяться и создавать групповые встречи.', ko: '그룹 모임을 둘러보고 참여하고 만들려면 트립 패스 또는 구독을 추가하세요.' },
  'Meet up with travelers from home.': { es: 'Reúnete con viajeros de tu país.', fr: 'Rencontrez des voyageurs de votre pays.', pt: 'Encontre-se com viajantes do seu país.', de: 'Triff Reisende aus deiner Heimat.', ja: '故郷の旅行者と会いましょう。', zh: '与来自家乡的旅行者相聚。', ar: 'التقِ بمسافرين من وطنك.', hi: 'अपने देश के यात्रियों से मिलें।', it: 'Incontra viaggiatori del tuo paese.', ru: 'Встречайтесь с путешественниками с родины.', ko: '고향에서 온 여행자들과 만나보세요.' },
  Create: { es: 'Crear', fr: 'Créer', pt: 'Criar', de: 'Erstellen', ja: '作成', zh: '创建', ar: 'إنشاء', hi: 'बनाएं', it: 'Crea', ru: 'Создать', ko: '만들기' },
  'My groups': { es: 'Mis grupos', fr: 'Mes groupes', pt: 'Meus grupos', de: 'Meine Gruppen', ja: 'マイグループ', zh: '我的群组', ar: 'مجموعاتي', hi: 'मेरे समूह', it: 'I miei gruppi', ru: 'Мои группы', ko: '내 그룹' },
  'Find a group by nationality': { es: 'Buscar un grupo por nacionalidad', fr: 'Trouver un groupe par nationalité', pt: 'Encontrar um grupo por nacionalidade', de: 'Gruppe nach Nationalität finden', ja: '国籍でグループを探す', zh: '按国籍查找群组', ar: 'ابحث عن مجموعة حسب الجنسية', hi: 'राष्ट्रीयता के अनुसार समूह खोजें', it: 'Trova un gruppo per nazionalità', ru: 'Найти группу по национальности', ko: '국적으로 그룹 찾기' },
  'Search nationality, like Brazil': { es: 'Busca una nacionalidad, como Brasil', fr: 'Recherchez une nationalité, comme Brésil', pt: 'Pesquise uma nacionalidade, como Brasil', de: 'Nationalität suchen, z. B. Brasilien', ja: '「ブラジル」のように国籍を検索', zh: '搜索国籍，例如“巴西”', ar: 'ابحث عن جنسية، مثل البرازيل', hi: 'राष्ट्रीयता खोजें, जैसे ब्राज़ील', it: 'Cerca una nazionalità, ad es. Brasile', ru: 'Введите национальность, например «Бразилия»', ko: '국적 검색 (예: 브라질)' },
  'No groups match that search yet.': { es: 'Aún no hay grupos que coincidan con esa búsqueda.', fr: 'Aucun groupe ne correspond encore à cette recherche.', pt: 'Ainda não há grupos que correspondam a essa busca.', de: 'Noch keine Gruppen passend zu dieser Suche.', ja: 'その検索に一致するグループはまだありません。', zh: '暂无与该搜索匹配的群组。', ar: 'لا توجد مجموعات مطابقة لهذا البحث بعد.', hi: 'अभी तक उस खोज से मेल खाने वाला कोई समूह नहीं है।', it: 'Nessun gruppo corrisponde ancora a questa ricerca.', ru: 'Пока нет групп, соответствующих этому поиску.', ko: '아직 검색 결과와 일치하는 그룹이 없습니다.' },
  '{count} going': { es: '{count} asistirán', fr: '{count} participants', pt: '{count} vão', de: '{count} nehmen teil', ja: '{count}人参加', zh: '{count}人参加', ar: '{count} سيحضرون', hi: '{count} जा रहे हैं', it: '{count} partecipanti', ru: 'Идут: {count}', ko: '{count}명 참여' },
  'Group not found.': { es: 'Grupo no encontrado.', fr: 'Groupe introuvable.', pt: 'Grupo não encontrado.', de: 'Gruppe nicht gefunden.', ja: 'グループが見つかりません。', zh: '未找到该群组。', ar: 'لم يتم العثور على المجموعة.', hi: 'समूह नहीं मिला।', it: 'Gruppo non trovato.', ru: 'Группа не найдена.', ko: '그룹을 찾을 수 없습니다.' },
  '(you)': { es: '(tú)', fr: '(vous)', pt: '(você)', de: '(du)', ja: '（あなた）', zh: '（你）', ar: '(أنت)', hi: '(आप)', it: '(tu)', ru: '(вы)', ko: '(나)' },
  '{nationality} nationality meetup': { es: 'Quedada de nacionalidad {nationality}', fr: 'Rencontre de nationalité {nationality}', pt: 'Encontro de nacionalidade {nationality}', de: '{nationality}-Nationalitätstreffen', ja: '{nationality}国籍の集まり', zh: '{nationality}国籍聚会', ar: 'تجمع لجنسية {nationality}', hi: '{nationality} राष्ट्रीयता मीटअप', it: 'Incontro di nazionalità {nationality}', ru: 'Встреча для национальности {nationality}', ko: '{nationality} 국적 모임' },
  'Group unavailable': { es: 'Grupo no disponible', fr: 'Groupe indisponible', pt: 'Grupo indisponível', de: 'Gruppe nicht verfügbar', ja: 'グループは利用できません', zh: '群组不可用', ar: 'المجموعة غير متاحة', hi: 'समूह अनुपलब्ध है', it: 'Gruppo non disponibile', ru: 'Группа недоступна', ko: '그룹을 사용할 수 없습니다' },
  "You've blocked the organizer of this group, so it's hidden from you.": { es: 'Has bloqueado al organizador de este grupo, por lo que está oculto para ti.', fr: 'Vous avez bloqué l’organisateur de ce groupe, il vous est donc masqué.', pt: 'Você bloqueou o organizador deste grupo, então ele está oculto para você.', de: 'Du hast den Organisator dieser Gruppe blockiert, daher ist sie für dich ausgeblendet.', ja: 'このグループの主催者をブロックしているため、非表示になっています。', zh: '您已屏蔽此群组的组织者，因此该群组对您隐藏。', ar: 'لقد حظرت منظم هذه المجموعة، لذا فهي مخفية عنك.', hi: 'आपने इस समूह के आयोजक को ब्लॉक कर दिया है, इसलिए यह आपसे छिपा है।', it: "Hai bloccato l'organizzatore di questo gruppo, quindi è nascosto per te.", ru: 'Вы заблокировали организатора этой группы, поэтому она скрыта от вас.', ko: '이 그룹의 주최자를 차단하여 그룹이 숨겨졌습니다.' },
  'Request sent': { es: 'Solicitud enviada', fr: 'Demande envoyée', pt: 'Solicitação enviada', de: 'Anfrage gesendet', ja: 'リクエスト送信済み', zh: '请求已发送', ar: 'تم إرسال الطلب', hi: 'अनुरोध भेजा गया', it: 'Richiesta inviata', ru: 'Запрос отправлен', ko: '요청 전송됨' },
  'Request to join': { es: 'Solicitar unirse', fr: 'Demander à rejoindre', pt: 'Solicitar para entrar', de: 'Beitritt anfragen', ja: '参加をリクエスト', zh: '申请加入', ar: 'طلب الانضمام', hi: 'शामिल होने का अनुरोध करें', it: 'Richiedi di unirti', ru: 'Запросить вступление', ko: '참여 요청' },
  'Leave group': { es: 'Salir del grupo', fr: 'Quitter le groupe', pt: 'Sair do grupo', de: 'Gruppe verlassen', ja: 'グループを退出', zh: '退出群组', ar: 'مغادرة المجموعة', hi: 'समूह छोड़ें', it: 'Lascia il gruppo', ru: 'Покинуть группу', ko: '그룹 나가기' },
  "Delete this group for everyone? This can't be undone.": { es: '¿Eliminar este grupo para todos? Esto no se puede deshacer.', fr: 'Supprimer ce groupe pour tout le monde ? Action irréversible.', pt: 'Excluir este grupo para todos? Isso não pode ser desfeito.', de: 'Diese Gruppe für alle löschen? Dies kann nicht rückgängig gemacht werden.', ja: 'このグループを全員に対して削除しますか？元に戻せません。', zh: '要为所有人删除此群组吗？此操作无法撤销。', ar: 'هل تريد حذف هذه المجموعة للجميع؟ لا يمكن التراجع عن هذا.', hi: 'सभी के लिए यह समूह हटाएं? इसे पूर्ववत नहीं किया जा सकता।', it: 'Eliminare questo gruppo per tutti? Non può essere annullato.', ru: 'Удалить эту группу для всех? Это действие нельзя отменить.', ko: '모두를 위해 이 그룹을 삭제하시겠습니까? 되돌릴 수 없습니다.' },
  'Deleting…': { es: 'Eliminando…', fr: 'Suppression…', pt: 'Excluindo…', de: 'Wird gelöscht…', ja: '削除中…', zh: '正在删除…', ar: 'جارٍ الحذف…', hi: 'हटाया जा रहा है…', it: 'Eliminazione…', ru: 'Удаление…', ko: '삭제 중…' },
  Delete: { es: 'Eliminar', fr: 'Supprimer', pt: 'Excluir', de: 'Löschen', ja: '削除', zh: '删除', ar: 'حذف', hi: 'हटाएं', it: 'Elimina', ru: 'Удалить', ko: '삭제' },
  'Delete group': { es: 'Eliminar grupo', fr: 'Supprimer le groupe', pt: 'Excluir grupo', de: 'Gruppe löschen', ja: 'グループを削除', zh: '删除群组', ar: 'حذف المجموعة', hi: 'समूह हटाएं', it: 'Elimina gruppo', ru: 'Удалить группу', ko: '그룹 삭제' },
  Decline: { es: 'Rechazar', fr: 'Refuser', pt: 'Recusar', de: 'Ablehnen', ja: '拒否', zh: '拒绝', ar: 'رفض', hi: 'अस्वीकार करें', it: 'Rifiuta', ru: 'Отклонить', ko: '거절' },
  Accept: { es: 'Aceptar', fr: 'Accepter', pt: 'Aceitar', de: 'Annehmen', ja: '承認', zh: '接受', ar: 'قبول', hi: 'स्वीकार करें', it: 'Accetta', ru: 'Принять', ko: '수락' },
  Members: { es: 'Miembros', fr: 'Membres', pt: 'Membros', de: 'Mitglieder', ja: 'メンバー', zh: '成员', ar: 'الأعضاء', hi: 'सदस्य', it: 'Membri', ru: 'Участники', ko: '멤버' },
  'Remove?': { es: '¿Eliminar?', fr: 'Retirer ?', pt: 'Remover?', de: 'Entfernen?', ja: '削除しますか？', zh: '要移除吗？', ar: 'إزالة؟', hi: 'हटाएं?', it: 'Rimuovere?', ru: 'Удалить?', ko: '제거할까요?' },
  Remove: { es: 'Eliminar', fr: 'Retirer', pt: 'Remover', de: 'Entfernen', ja: '削除', zh: '移除', ar: 'إزالة', hi: 'हटाएं', it: 'Rimuovi', ru: 'Удалить', ko: '제거' },
  'Remove member': { es: 'Eliminar miembro', fr: 'Retirer le membre', pt: 'Remover membro', de: 'Mitglied entfernen', ja: 'メンバーを削除', zh: '移除成员', ar: 'إزالة العضو', hi: 'सदस्य हटाएं', it: 'Rimuovi membro', ru: 'Удалить участника', ko: '멤버 제거' },
  '{rating} ({count})': { es: '{rating} ({count})', fr: '{rating} ({count})', pt: '{rating} ({count})', de: '{rating} ({count})', ja: '{rating}（{count}件）', zh: '{rating}（{count}条）', ar: '{rating} ({count})', hi: '{rating} ({count})', it: '{rating} ({count})', ru: '{rating} ({count})', ko: '{rating}（{count}개）' },
  'Approximate area only, {city} · exact spot shared once you join': { es: 'Solo área aproximada, {city} · la ubicación exacta se comparte al unirte', fr: 'Zone approximative uniquement, {city} · le lieu exact est partagé une fois inscrit', pt: 'Apenas área aproximada, {city} · o local exato é compartilhado ao entrar', de: 'Nur ungefähre Gegend, {city} · genauer Ort wird nach Beitritt geteilt', ja: 'おおよそのエリアのみ、{city}・参加後に正確な場所が共有されます', zh: '仅显示大致区域，{city}，加入后将分享具体地点', ar: 'منطقة تقريبية فقط، {city} · يتم مشاركة الموقع الدقيق عند الانضمام', hi: 'केवल अनुमानित क्षेत्र, {city} · शामिल होने पर सटीक स्थान साझा किया जाएगा', it: 'Solo area approssimativa, {city} · la posizione esatta viene condivisa una volta iscritti', ru: 'Показан только приблизительный район, {city} · точное место будет доступно после вступления', ko: '대략적인 지역만 표시됨, {city} · 참여 시 정확한 위치가 공유됩니다' },
  'Free access is capped at {limit} group join requests a week. Add a plan for unlimited groups.': { es: 'El acceso gratuito está limitado a {limit} solicitudes de grupo por semana. Añade un plan para grupos ilimitados.', fr: "L'accès gratuit est limité à {limit} demandes de groupe par semaine. Ajoutez un forfait pour des groupes illimités.", pt: 'O acesso gratuito é limitado a {limit} solicitações de grupo por semana. Adicione um plano para grupos ilimitados.', de: 'Der kostenlose Zugang ist auf {limit} Gruppenanfragen pro Woche begrenzt. Füge einen Tarif für unbegrenzte Gruppen hinzu.', ja: '無料プランは週{limit}件のグループ参加リクエストに制限されています。無制限にするにはプランを追加してください。', zh: '免费用户每周限{limit}次群组加入请求，添加套餐以无限使用群组功能。', ar: 'يقتصر الوصول المجاني على {limit} طلبات انضمام للمجموعات أسبوعيًا. أضف خطة لمجموعات غير محدودة.', hi: 'निःशुल्क एक्सेस प्रति सप्ताह {limit} समूह अनुरोधों तक सीमित है। असीमित समूहों के लिए योजना जोड़ें।', it: "L'accesso gratuito è limitato a {limit} richieste di gruppo a settimana. Aggiungi un piano per gruppi illimitati.", ru: 'Бесплатный доступ ограничен {limit} запросами на вступление в группы в неделю. Добавьте тариф для безлимитных групп.', ko: '무료 이용은 주당 {limit}회 그룹 참여 요청으로 제한됩니다. 무제한 그룹 이용을 원하시면 요금제를 추가하세요.' },
  'Requests to join ({count})': { es: 'Solicitudes para unirse ({count})', fr: 'Demandes pour rejoindre ({count})', pt: 'Solicitações para entrar ({count})', de: 'Beitrittsanfragen ({count})', ja: '参加リクエスト（{count}件）', zh: '加入请求（{count}）', ar: 'طلبات الانضمام ({count})', hi: 'शामिल होने के अनुरोध ({count})', it: 'Richieste di adesione ({count})', ru: 'Запросы на вступление ({count})', ko: '참여 요청（{count}）' },
  'Trip passes cover up to 14 days. Renew your plan to see meetup locations again.': { es: 'Los pases de viaje cubren hasta 14 días. Renueva tu plan para volver a ver las ubicaciones de las quedadas.', fr: 'Les pass voyage couvrent jusqu’à 14 jours. Renouvelez votre forfait pour revoir les lieux de rencontre.', pt: 'Os passes de viagem cobrem até 14 dias. Renove seu plano para ver os locais dos encontros novamente.', de: 'Reisepässe gelten für bis zu 14 Tage. Erneuere deinen Tarif, um Treffpunkte wieder zu sehen.', ja: 'トリップパスは最大14日間有効です。プランを更新して集合場所を再度確認しましょう。', zh: '旅行通行证最多可使用14天。续订套餐以重新查看聚会地点。', ar: 'تغطي تذاكر الرحلات حتى 14 يومًا. جدد خطتك لرؤية مواقع التجمعات مرة أخرى.', hi: 'ट्रिप पास 14 दिनों तक मान्य हैं। मीटअप स्थान फिर से देखने के लिए अपनी योजना नवीनीकृत करें।', it: 'I pass viaggio coprono fino a 14 giorni. Rinnova il tuo piano per rivedere le località degli incontri.', ru: 'Тревел-пропуск действует до 14 дней. Продлите тариф, чтобы снова видеть места встреч.', ko: '트립 패스는 최대 14일간 이용 가능합니다. 모임 장소를 다시 보려면 요금제를 갱신하세요.' },
  'Add a Trip Pass or subscription to see meetup locations and join in.': { es: 'Añade un pase de viaje o suscripción para ver ubicaciones de quedadas y unirte.', fr: 'Ajoutez un pass voyage ou un abonnement pour voir les lieux de rencontre et participer.', pt: 'Adicione um passe de viagem ou assinatura para ver locais de encontro e participar.', de: 'Füge einen Reisepass oder ein Abo hinzu, um Treffpunkte zu sehen und teilzunehmen.', ja: 'トリップパスまたはサブスクリプションを追加して、集合場所を見て参加しましょう。', zh: '添加旅行通行证或订阅，即可查看聚会地点并加入。', ar: 'أضف تذكرة رحلة أو اشتراكًا لرؤية مواقع التجمعات والانضمام إليها.', hi: 'मीटअप स्थान देखने और शामिल होने के लिए ट्रिप पास या सदस्यता जोड़ें।', it: 'Aggiungi un pass viaggio o un abbonamento per vedere le località degli incontri e partecipare.', ru: 'Добавьте тревел-пропуск или подписку, чтобы видеть места встреч и присоединяться.', ko: '모임 장소를 보고 참여하려면 트립 패스 또는 구독을 추가하세요.' },
  'Pick a date for the meetup.': { es: 'Elige una fecha para la quedada.', fr: 'Choisissez une date pour la rencontre.', pt: 'Escolha uma data para o encontro.', de: 'Wähle ein Datum für das Treffen.', ja: '集まりの日程を選んでください。', zh: '请为聚会选择一个日期。', ar: 'اختر تاريخًا للتجمع.', hi: 'मीटअप के लिए एक तारीख चुनें।', it: "Scegli una data per l'incontro.", ru: 'Выберите дату для встречи.', ko: '모임 날짜를 선택하세요.' },
  '← Back to groups': { es: '← Volver a grupos', fr: '← Retour aux groupes', pt: '← Voltar aos grupos', de: '← Zurück zu Gruppen', ja: '← グループに戻る', zh: '← 返回群组', ar: '← العودة إلى المجموعات', hi: '← समूहों पर वापस जाएं', it: '← Torna ai gruppi', ru: '← Назад к группам', ko: '← 그룹으로 돌아가기' },
  'Create a group': { es: 'Crear un grupo', fr: 'Créer un groupe', pt: 'Criar um grupo', de: 'Gruppe erstellen', ja: 'グループを作成', zh: '创建群组', ar: 'إنشاء مجموعة', hi: 'समूह बनाएं', it: 'Crea un gruppo', ru: 'Создать группу', ko: '그룹 만들기' },
  'Start a meetup for travelers of your nationality nearby.': { es: 'Inicia una quedada para viajeros de tu nacionalidad cercanos.', fr: 'Organisez une rencontre pour des voyageurs de votre nationalité à proximité.', pt: 'Comece um encontro para viajantes da sua nacionalidade por perto.', de: 'Starte ein Treffen für Reisende deiner Nationalität in der Nähe.', ja: '近くにいる同じ国籍の旅行者のための集まりを始めましょう。', zh: '为附近同国籍的旅行者发起一场聚会。', ar: 'ابدأ تجمعًا للمسافرين من جنسيتك القريبين منك.', hi: 'आस-पास अपनी राष्ट्रीयता के यात्रियों के लिए मीटअप शुरू करें।', it: 'Avvia un incontro per viaggiatori della tua nazionalità nelle vicinanze.', ru: 'Организуйте встречу для путешественников вашей национальности поблизости.', ko: '근처의 같은 국적 여행자를 위한 모임을 시작하세요.' },
  'Group name': { es: 'Nombre del grupo', fr: 'Nom du groupe', pt: 'Nome do grupo', de: 'Gruppenname', ja: 'グループ名', zh: '群组名称', ar: 'اسم المجموعة', hi: 'समूह का नाम', it: 'Nome del gruppo', ru: 'Название группы', ko: '그룹 이름' },
  'Aussies in Lisbon': { es: 'Australianos en Lisboa', fr: 'Australiens à Lisbonne', pt: 'Australianos em Lisboa', de: 'Australier in Lissabon', ja: 'リスボンのオーストラリア人', zh: '里斯本的澳洲人', ar: 'أستراليون في لشبونة', hi: 'लिस्बन में ऑस्ट्रेलियाई', it: 'Australiani a Lisbona', ru: 'Австралийцы в Лиссабоне', ko: '리스본의 호주인' },
  Nationality: { es: 'Nacionalidad', fr: 'Nationalité', pt: 'Nacionalidade', de: 'Nationalität', ja: '国籍', zh: '国籍', ar: 'الجنسية', hi: 'राष्ट्रीयता', it: 'Nazionalità', ru: 'Национальность', ko: '국적' },
  'Select a nationality': { es: 'Selecciona una nacionalidad', fr: 'Sélectionnez une nationalité', pt: 'Selecione uma nacionalidade', de: 'Nationalität auswählen', ja: '国籍を選択', zh: '选择国籍', ar: 'اختر جنسية', hi: 'राष्ट्रीयता चुनें', it: 'Seleziona una nazionalità', ru: 'Выберите национальность', ko: '국적 선택' },
  City: { es: 'Ciudad', fr: 'Ville', pt: 'Cidade', de: 'Stadt', ja: '都市', zh: '城市', ar: 'المدينة', hi: 'शहर', it: 'Città', ru: 'Город', ko: '도시' },
  'Meetup date': { es: 'Fecha de la quedada', fr: 'Date de la rencontre', pt: 'Data do encontro', de: 'Treffdatum', ja: '集まりの日程', zh: '聚会日期', ar: 'تاريخ التجمع', hi: 'मीटअप की तारीख', it: "Data dell'incontro", ru: 'Дата встречи', ko: '모임 날짜' },
  'When are you meeting?': { es: '¿Cuándo se reunirán?', fr: 'Quand vous rencontrez-vous ?', pt: 'Quando vocês vão se encontrar?', de: 'Wann trefft ihr euch?', ja: 'いつ集まりますか？', zh: '您们何时聚会？', ar: 'متى ستلتقون؟', hi: 'आप कब मिल रहे हैं?', it: 'Quando vi incontrate?', ru: 'Когда состоится встреча?', ko: '언제 만나나요?' },
  Description: { es: 'Descripción', fr: 'Description', pt: 'Descrição', de: 'Beschreibung', ja: '説明', zh: '描述', ar: 'الوصف', hi: 'विवरण', it: 'Descrizione', ru: 'Описание', ko: '설명' },
  'Exact location stays hidden until someone joins.': { es: 'La ubicación exacta permanece oculta hasta que alguien se une.', fr: "L'emplacement exact reste masqué jusqu'à ce que quelqu'un rejoigne.", pt: 'A localização exata fica oculta até alguém entrar.', de: 'Der genaue Ort bleibt verborgen, bis jemand beitritt.', ja: '誰かが参加するまで正確な場所は非表示のままです。', zh: '在有人加入之前，具体地点保持隐藏。', ar: 'يبقى الموقع الدقيق مخفيًا حتى ينضم أحدهم.', hi: 'जब तक कोई शामिल नहीं होता, सटीक स्थान छिपा रहता है।', it: "La posizione esatta resta nascosta finché qualcuno non si unisce.", ru: 'Точное место остаётся скрытым, пока кто-то не присоединится.', ko: '누군가 참여하기 전까지 정확한 위치는 표시되지 않습니다.' },
  "What's the plan?": { es: '¿Cuál es el plan?', fr: 'Quel est le programme ?', pt: 'Qual é o plano?', de: 'Was ist geplant?', ja: '予定を教えてください', zh: '有什么计划？', ar: 'ما هي الخطة؟', hi: 'योजना क्या है?', it: 'Qual è il programma?', ru: 'Какие планы?', ko: '어떤 계획인가요?' },
  'Create group': { es: 'Crear grupo', fr: 'Créer le groupe', pt: 'Criar grupo', de: 'Gruppe erstellen', ja: 'グループを作成', zh: '创建群组', ar: 'إنشاء المجموعة', hi: 'समूह बनाएं', it: 'Crea gruppo', ru: 'Создать группу', ko: '그룹 만들기' },
  'Trip passes cover up to 14 days. Renew your plan to create a group meetup.': { es: 'Los pases de viaje cubren hasta 14 días. Renueva tu plan para crear una quedada de grupo.', fr: 'Les pass voyage couvrent jusqu’à 14 jours. Renouvelez votre forfait pour créer une rencontre de groupe.', pt: 'Os passes de viagem cobrem até 14 dias. Renove seu plano para criar um encontro de grupo.', de: 'Reisepässe gelten für bis zu 14 Tage. Erneuere deinen Tarif, um ein Gruppentreffen zu erstellen.', ja: 'トリップパスは最大14日間有効です。プランを更新してグループの集まりを作成しましょう。', zh: '旅行通行证最多可使用14天。续订套餐以创建群组聚会。', ar: 'تغطي تذاكر الرحلات حتى 14 يومًا. جدد خطتك لإنشاء تجمع مجموعة.', hi: 'ट्रिप पास 14 दिनों तक मान्य हैं। समूह मीटअप बनाने के लिए अपनी योजना नवीनीकृत करें।', it: 'I pass viaggio coprono fino a 14 giorni. Rinnova il tuo piano per creare un incontro di gruppo.', ru: 'Тревел-пропуск действует до 14 дней. Продлите тариф, чтобы создать групповую встречу.', ko: '트립 패스는 최대 14일간 이용 가능합니다. 그룹 모임을 만들려면 요금제를 갱신하세요.' },
  'Add a Trip Pass or subscription to create a group meetup.': { es: 'Añade un pase de viaje o suscripción para crear una quedada de grupo.', fr: 'Ajoutez un pass voyage ou un abonnement pour créer une rencontre de groupe.', pt: 'Adicione um passe de viagem ou assinatura para criar um encontro de grupo.', de: 'Füge einen Reisepass oder ein Abo hinzu, um ein Gruppentreffen zu erstellen.', ja: 'トリップパスまたはサブスクリプションを追加して、グループの集まりを作成しましょう。', zh: '添加旅行通行证或订阅，即可创建群组聚会。', ar: 'أضف تذكرة رحلة أو اشتراكًا لإنشاء تجمع مجموعة.', hi: 'समूह मीटअप बनाने के लिए ट्रिप पास या सदस्यता जोड़ें।', it: 'Aggiungi un pass viaggio o un abbonamento per creare un incontro di gruppo.', ru: 'Добавьте тревел-пропуск или подписку, чтобы создать групповую встречу.', ko: '그룹 모임을 만들려면 트립 패스 또는 구독을 추가하세요.' },

  // --- Messages / chat ----------------------------------------------
  'Matches you message will show up here.': { es: 'Los matches con los que hables aparecerán aquí.', fr: 'Les matchs à qui vous écrivez apparaîtront ici.', pt: 'Os matches com quem você conversar aparecerão aqui.', de: 'Matches, denen du schreibst, erscheinen hier.', ja: 'メッセージを送ったマッチがここに表示されます。', zh: '您发消息的配对对象会显示在此处。', ar: 'ستظهر هنا المطابقات التي تراسلها.', hi: 'आप जिन मैचों को संदेश भेजते हैं वे यहां दिखाई देंगे।', it: 'I match a cui scrivi appariranno qui.', ru: 'Здесь появятся совпадения, которым вы написали.', ko: '메시지를 보낸 매칭 상대가 여기에 표시됩니다.' },
  Photo: { es: 'Foto', fr: 'Photo', pt: 'Foto', de: 'Foto', ja: '写真', zh: '照片', ar: 'صورة', hi: 'फ़ोटो', it: 'Foto', ru: 'Фото', ko: '사진' },
  Attachment: { es: 'Archivo adjunto', fr: 'Pièce jointe', pt: 'Anexo', de: 'Anhang', ja: '添付ファイル', zh: '附件', ar: 'مرفق', hi: 'अनुलग्नक', it: 'Allegato', ru: 'Вложение', ko: '첨부파일' },
  'Say hello': { es: 'Saluda', fr: 'Dites bonjour', pt: 'Diga oi', de: 'Sag hallo', ja: '挨拶する', zh: '打个招呼', ar: 'قل مرحبًا', hi: 'नमस्ते कहें', it: 'Saluta', ru: 'Поздороваться', ko: '인사하기' },
  "Couldn't attach that file.": { es: 'No se pudo adjuntar ese archivo.', fr: "Impossible de joindre ce fichier.", pt: 'Não foi possível anexar esse arquivo.', de: 'Diese Datei konnte nicht angehängt werden.', ja: 'そのファイルを添付できませんでした。', zh: '无法附加该文件。', ar: 'تعذر إرفاق هذا الملف.', hi: 'उस फ़ाइल को संलग्न नहीं किया जा सका।', it: 'Impossibile allegare quel file.', ru: 'Не удалось прикрепить этот файл.', ko: '해당 파일을 첨부할 수 없습니다.' },
  Unblock: { es: 'Desbloquear', fr: 'Débloquer', pt: 'Desbloquear', de: 'Entsperren', ja: 'ブロック解除', zh: '取消屏蔽', ar: 'إلغاء الحظر', hi: 'अनब्लॉक करें', it: 'Sblocca', ru: 'Разблокировать', ko: '차단 해제' },
  'Remove attachment': { es: 'Eliminar archivo adjunto', fr: 'Retirer la pièce jointe', pt: 'Remover anexo', de: 'Anhang entfernen', ja: '添付を削除', zh: '移除附件', ar: 'إزالة المرفق', hi: 'अनुलग्नक हटाएं', it: 'Rimuovi allegato', ru: 'Удалить вложение', ko: '첨부파일 제거' },
  'Attach a photo or file': { es: 'Adjuntar una foto o archivo', fr: 'Joindre une photo ou un fichier', pt: 'Anexar uma foto ou arquivo', de: 'Foto oder Datei anhängen', ja: '写真またはファイルを添付', zh: '附加照片或文件', ar: 'إرفاق صورة أو ملف', hi: 'फ़ोटो या फ़ाइल संलग्न करें', it: 'Allega una foto o un file', ru: 'Прикрепить фото или файл', ko: '사진 또는 파일 첨부' },
  Message: { es: 'Mensaje', fr: 'Message', pt: 'Mensagem', de: 'Nachricht', ja: 'メッセージ', zh: '消息', ar: 'رسالة', hi: 'संदेश', it: 'Messaggio', ru: 'Сообщение', ko: '메시지' },
  Send: { es: 'Enviar', fr: 'Envoyer', pt: 'Enviar', de: 'Senden', ja: '送信', zh: '发送', ar: 'إرسال', hi: 'भेजें', it: 'Invia', ru: 'Отправить', ko: '전송' },
  File: { es: 'Archivo', fr: 'Fichier', pt: 'Arquivo', de: 'Datei', ja: 'ファイル', zh: '文件', ar: 'ملف', hi: 'फ़ाइल', it: 'File', ru: 'Файл', ko: '파일' },
  'Loading…': { es: 'Cargando…', fr: 'Chargement…', pt: 'Carregando…', de: 'Wird geladen…', ja: '読み込み中…', zh: '加载中…', ar: 'جارٍ التحميل…', hi: 'लोड हो रहा है…', it: 'Caricamento…', ru: 'Загрузка…', ko: '로딩 중…' },
  'Conversation not found.': { es: 'Conversación no encontrada.', fr: 'Conversation introuvable.', pt: 'Conversa não encontrada.', de: 'Unterhaltung nicht gefunden.', ja: '会話が見つかりません。', zh: '未找到该对话。', ar: 'لم يتم العثور على المحادثة.', hi: 'बातचीत नहीं मिली।', it: 'Conversazione non trovata.', ru: 'Беседа не найдена.', ko: '대화를 찾을 수 없습니다.' },
  'Say hi to {name}.': { es: 'Saluda a {name}.', fr: 'Dites bonjour à {name}.', pt: 'Diga oi para {name}.', de: 'Sag {name} hallo.', ja: '{name}さんに挨拶しましょう。', zh: '向{name}打个招呼。', ar: 'قل مرحبًا لـ {name}.', hi: '{name} को नमस्ते कहें।', it: 'Saluta {name}.', ru: 'Поздоровайтесь с {name}.', ko: '{name}님에게 인사해 보세요.' },
  "You've blocked {name}. Unblock to send messages.": { es: 'Has bloqueado a {name}. Desbloquea para enviar mensajes.', fr: 'Vous avez bloqué {name}. Débloquez pour envoyer des messages.', pt: 'Você bloqueou {name}. Desbloqueie para enviar mensagens.', de: 'Du hast {name} blockiert. Zum Senden von Nachrichten entsperren.', ja: '{name}さんをブロックしています。メッセージを送るにはブロックを解除してください。', zh: '您已屏蔽{name}。取消屏蔽后即可发送消息。', ar: 'لقد حظرت {name}. ألغِ الحظر لإرسال الرسائل.', hi: 'आपने {name} को ब्लॉक कर दिया है। संदेश भेजने के लिए अनब्लॉक करें।', it: 'Hai bloccato {name}. Sblocca per inviare messaggi.', ru: 'Вы заблокировали {name}. Разблокируйте, чтобы отправлять сообщения.', ko: '{name}님을 차단했습니다. 메시지를 보내려면 차단을 해제하세요.' },

  // --- Notifications ----------------------------------------------------
  'Likes, matches, and messages will show up here.': { es: 'Los me gusta, matches y mensajes aparecerán aquí.', fr: 'Les likes, matchs et messages apparaîtront ici.', pt: 'Curtidas, matches e mensagens aparecerão aqui.', de: 'Gefällt-mir-Angaben, Matches und Nachrichten erscheinen hier.', ja: 'いいね、マッチ、メッセージがここに表示されます。', zh: '点赞、配对和消息将显示在此处。', ar: 'ستظهر هنا الإعجابات والمطابقات والرسائل.', hi: 'लाइक, मैच और संदेश यहां दिखाई देंगे।', it: 'Mi piace, match e messaggi appariranno qui.', ru: 'Здесь появятся лайки, совпадения и сообщения.', ko: '좋아요, 매칭, 메시지가 여기에 표시됩니다.' },
  '{name} liked your post': { es: '{name} le dio me gusta a tu publicación', fr: '{name} a aimé votre publication', pt: '{name} curtiu sua publicação', de: '{name} gefällt dein Beitrag', ja: '{name}さんがあなたの投稿にいいねしました', zh: '{name}赞了您的帖子', ar: 'أعجب {name} بمنشورك', hi: '{name} ने आपकी पोस्ट पसंद की', it: 'A {name} piace il tuo post', ru: '{name} понравился ваш пост', ko: '{name}님이 회원님의 게시물을 좋아합니다' },
  '{name} swiped right on you': { es: '{name} te dio like', fr: '{name} vous a liké', pt: '{name} deu like em você', de: '{name} hat dich geliked', ja: '{name}さんがあなたにいいねしました', zh: '{name}对您表示喜欢', ar: 'أعجب بك {name}', hi: '{name} ने आपको पसंद किया', it: '{name} ti ha messo mi piace', ru: '{name} поставил(а) вам лайк', ko: '{name}님이 회원님을 좋아합니다' },
  '{name}: {preview}': { es: '{name}: {preview}', fr: '{name} : {preview}', pt: '{name}: {preview}', de: '{name}: {preview}', ja: '{name}：{preview}', zh: '{name}：{preview}', ar: '{name}: {preview}', hi: '{name}: {preview}', it: '{name}: {preview}', ru: '{name}: {preview}', ko: '{name}: {preview}' },
  Dismiss: { es: 'Descartar', fr: 'Ignorer', pt: 'Dispensar', de: 'Verwerfen', ja: '閉じる', zh: '关闭', ar: 'تجاهل', hi: 'खारिज करें', it: 'Ignora', ru: 'Скрыть', ko: '닫기' },
  Someone: { es: 'Alguien', fr: "Quelqu'un", pt: 'Alguém', de: 'Jemand', ja: '誰か', zh: '有人', ar: 'شخص ما', hi: 'कोई', it: 'Qualcuno', ru: 'Кто-то', ko: '누군가' },
  'sent you a message': { es: 'te envió un mensaje', fr: 'vous a envoyé un message', pt: 'enviou uma mensagem para você', de: 'hat dir eine Nachricht gesendet', ja: 'メッセージを送りました', zh: '给您发送了一条消息', ar: 'أرسل لك رسالة', hi: 'आपको एक संदेश भेजा', it: 'ti ha inviato un messaggio', ru: 'отправил(а) вам сообщение', ko: '메시지를 보냈습니다' },

  // --- Search -------------------------------------------------------
  'Search is locked': { es: 'La búsqueda está bloqueada', fr: 'La recherche est verrouillée', pt: 'A pesquisa está bloqueada', de: 'Suche ist gesperrt', ja: '検索はロックされています', zh: '搜索已锁定', ar: 'البحث مقفل', hi: 'खोज लॉक है', it: 'La ricerca è bloccata', ru: 'Поиск заблокирован', ko: '검색이 잠겨 있습니다' },
  'Trip passes cover up to 14 days. Renew your plan to search for other travelers.': { es: 'Los pases de viaje cubren hasta 14 días. Renueva tu plan para buscar otros viajeros.', fr: 'Les pass voyage couvrent jusqu’à 14 jours. Renouvelez votre forfait pour rechercher d’autres voyageurs.', pt: 'Os passes de viagem cobrem até 14 dias. Renove seu plano para pesquisar outros viajantes.', de: 'Reisepässe gelten für bis zu 14 Tage. Erneuere deinen Tarif, um nach anderen Reisenden zu suchen.', ja: 'トリップパスは最大14日間有効です。プランを更新して他の旅行者を検索しましょう。', zh: '旅行通行证最多可使用14天。续订套餐以搜索其他旅行者。', ar: 'تغطي تذاكر الرحلات حتى 14 يومًا. جدد خطتك للبحث عن مسافرين آخرين.', hi: 'ट्रिप पास 14 दिनों तक मान्य हैं। अन्य यात्रियों को खोजने के लिए अपनी योजना नवीनीकृत करें।', it: 'I pass viaggio coprono fino a 14 giorni. Rinnova il tuo piano per cercare altri viaggiatori.', ru: 'Тревел-пропуск действует до 14 дней. Продлите тариф, чтобы искать других путешественников.', ko: '트립 패스는 최대 14일간 이용 가능합니다. 다른 여행자를 검색하려면 요금제를 갱신하세요.' },
  'Search by name or nationality': { es: 'Buscar por nombre o nacionalidad', fr: 'Rechercher par nom ou nationalité', pt: 'Pesquisar por nome ou nacionalidade', de: 'Nach Name oder Nationalität suchen', ja: '名前または国籍で検索', zh: '按姓名或国籍搜索', ar: 'ابحث بالاسم أو الجنسية', hi: 'नाम या राष्ट्रीयता से खोजें', it: 'Cerca per nome o nazionalità', ru: 'Поиск по имени или национальности', ko: '이름 또는 국적으로 검색' },
  'No one matches that search.': { es: 'Nadie coincide con esa búsqueda.', fr: 'Personne ne correspond à cette recherche.', pt: 'Ninguém corresponde a essa pesquisa.', de: 'Niemand passt zu dieser Suche.', ja: 'その検索に一致する人はいません。', zh: '没有与该搜索匹配的人。', ar: 'لا يوجد أحد يطابق هذا البحث.', hi: 'उस खोज से कोई मेल नहीं खाता।', it: 'Nessuno corrisponde a questa ricerca.', ru: 'Никто не соответствует этому поиску.', ko: '검색 결과와 일치하는 사람이 없습니다.' },
  '{count} more result hidden': { es: '{count} resultado más oculto', fr: '{count} résultat supplémentaire masqué', pt: '{count} resultado a mais oculto', de: '{count} weiteres Ergebnis ausgeblendet', ja: 'あと{count}件の結果が非表示です', zh: '还有{count}个结果被隐藏', ar: 'نتيجة إضافية واحدة ({count}) مخفية', hi: '{count} और परिणाम छिपे हुए', it: '{count} altro risultato nascosto', ru: 'Скрыт ещё {count} результат', ko: '{count}개의 추가 결과가 숨겨짐' },
  '{count} more results hidden': { es: '{count} resultados más ocultos', fr: '{count} résultats supplémentaires masqués', pt: '{count} resultados a mais ocultos', de: '{count} weitere Ergebnisse ausgeblendet', ja: 'あと{count}件の結果が非表示です', zh: '还有{count}个结果被隐藏', ar: '{count} نتائج إضافية مخفية', hi: '{count} और परिणाम छिपे हुए', it: '{count} altri risultati nascosti', ru: 'Скрыто ещё {count} результатов', ko: '{count}개의 추가 결과가 숨겨짐' },
  'Free search is limited to {limit} people. Add a plan to see everyone.': { es: 'La búsqueda gratuita está limitada a {limit} personas. Añade un plan para ver a todos.', fr: 'La recherche gratuite est limitée à {limit} personnes. Ajoutez un forfait pour voir tout le monde.', pt: 'A pesquisa gratuita é limitada a {limit} pessoas. Adicione um plano para ver todos.', de: 'Die kostenlose Suche ist auf {limit} Personen begrenzt. Füge einen Tarif hinzu, um alle zu sehen.', ja: '無料検索は{limit}人までに制限されています。全員を見るにはプランを追加してください。', zh: '免费搜索仅限{limit}人，添加套餐即可查看所有人。', ar: 'يقتصر البحث المجاني على {limit} أشخاص. أضف خطة لرؤية الجميع.', hi: 'निःशुल्क खोज {limit} लोगों तक सीमित है। सभी को देखने के लिए योजना जोड़ें।', it: 'La ricerca gratuita è limitata a {limit} persone. Aggiungi un piano per vedere tutti.', ru: 'Бесплатный поиск ограничен {limit} людьми. Добавьте тариф, чтобы видеть всех.', ko: '무료 검색은 {limit}명으로 제한됩니다. 모두를 보려면 요금제를 추가하세요.' },

  // --- Profile screen -----------------------------------------------
  Posts: { es: 'Publicaciones', fr: 'Publications', pt: 'Publicações', de: 'Beiträge', ja: '投稿', zh: '帖子', ar: 'المنشورات', hi: 'पोस्ट', it: 'Post', ru: 'Публикации', ko: '게시물' },
  Matches: { es: 'Matches', fr: 'Matchs', pt: 'Matches', de: 'Matches', ja: 'マッチ', zh: '配对', ar: 'المطابقات', hi: 'मैच', it: 'Match', ru: 'Совпадения', ko: '매칭' },
  'Edit profile': { es: 'Editar perfil', fr: 'Modifier le profil', pt: 'Editar perfil', de: 'Profil bearbeiten', ja: 'プロフィールを編集', zh: '编辑资料', ar: 'تعديل الملف الشخصي', hi: 'प्रोफ़ाइल संपादित करें', it: 'Modifica profilo', ru: 'Редактировать профиль', ko: '프로필 편집' },
  'Frequent Traveler': { es: 'Viajero frecuente', fr: 'Grand voyageur', pt: 'Viajante frequente', de: 'Vielreisender', ja: '頻繁な旅行者', zh: '常旅客', ar: 'مسافر متكرر', hi: 'बार-बार यात्रा करने वाला', it: 'Viaggiatore frequente', ru: 'Частый путешественник', ko: '단골 여행자' },
  'Trip Pass': { es: 'Pase de viaje', fr: 'Pass voyage', pt: 'Passe de viagem', de: 'Reisepass', ja: 'トリップパス', zh: '旅行通行证', ar: 'تذكرة رحلة', hi: 'ट्रिप पास', it: 'Pass viaggio', ru: 'Тревел-пропуск', ko: '트립 패스' },
  Expired: { es: 'Vencido', fr: 'Expiré', pt: 'Expirado', de: 'Abgelaufen', ja: '期限切れ', zh: '已过期', ar: 'منتهي', hi: 'समाप्त', it: 'Scaduto', ru: 'Истёк', ko: '만료됨' },
  Active: { es: 'Activo', fr: 'Actif', pt: 'Ativo', de: 'Aktiv', ja: '有効', zh: '有效', ar: 'نشط', hi: 'सक्रिय', it: 'Attivo', ru: 'Активен', ko: '활성' },
  'Your 14-day pass window has closed.': { es: 'Tu período de 14 días ha finalizado.', fr: 'Votre période de 14 jours est terminée.', pt: 'Seu período de 14 dias terminou.', de: 'Dein 14-Tage-Fenster ist abgelaufen.', ja: '14日間の期間が終了しました。', zh: '您的14天有效期已结束。', ar: 'انتهت فترة الـ14 يومًا الخاصة بك.', hi: 'आपकी 14-दिन की अवधि समाप्त हो गई है।', it: 'La tua finestra di 14 giorni è scaduta.', ru: 'Ваш 14-дневный период закончился.', ko: '14일 이용 기간이 종료되었습니다.' },
  'Renew plan': { es: 'Renovar plan', fr: 'Renouveler le forfait', pt: 'Renovar plano', de: 'Tarif erneuern', ja: 'プランを更新', zh: '续订套餐', ar: 'تجديد الخطة', hi: 'योजना नवीनीकृत करें', it: 'Rinnova piano', ru: 'Продлить тариф', ko: '요금제 갱신' },
  'Manage plan': { es: 'Gestionar plan', fr: 'Gérer le forfait', pt: 'Gerenciar plano', de: 'Tarif verwalten', ja: 'プランを管理', zh: '管理套餐', ar: 'إدارة الخطة', hi: 'योजना प्रबंधित करें', it: 'Gestisci piano', ru: 'Управлять тарифом', ko: '요금제 관리' },
  'No active plan': { es: 'Sin plan activo', fr: 'Aucun forfait actif', pt: 'Nenhum plano ativo', de: 'Kein aktiver Tarif', ja: '有効なプランがありません', zh: '暂无有效套餐', ar: 'لا توجد خطة نشطة', hi: 'कोई सक्रिय योजना नहीं', it: 'Nessun piano attivo', ru: 'Нет активного тарифа', ko: '활성 요금제 없음' },
  Free: { es: 'Gratis', fr: 'Gratuit', pt: 'Grátis', de: 'Kostenlos', ja: '無料', zh: '免费', ar: 'مجاني', hi: 'मुफ़्त', it: 'Gratis', ru: 'Бесплатно', ko: '무료' },
  "You're browsing Natio without a Trip Pass or subscription. Add one whenever you're ready.": { es: 'Estás explorando Natio sin un pase de viaje o suscripción. Añade uno cuando estés listo.', fr: 'Vous parcourez Natio sans pass voyage ni abonnement. Ajoutez-en un quand vous serez prêt.', pt: 'Você está navegando no Natio sem passe de viagem ou assinatura. Adicione um quando estiver pronto.', de: 'Du nutzt Natio ohne Reisepass oder Abo. Füge einen hinzu, sobald du bereit bist.', ja: 'トリップパスまたはサブスクリプションなしでNatioを閲覧しています。準備ができたら追加してください。', zh: '您目前未订阅旅行通行证或订阅套餐浏览Natio。准备好后可随时添加。', ar: 'أنت تتصفح Natio دون تذكرة رحلة أو اشتراك. أضف واحدة عندما تكون مستعدًا.', hi: 'आप बिना ट्रिप पास या सदस्यता के Natio ब्राउज़ कर रहे हैं। जब तैयार हों तब एक जोड़ें।', it: 'Stai navigando su Natio senza pass viaggio o abbonamento. Aggiungine uno quando sei pronto.', ru: 'Вы просматриваете Natio без тревел-пропуска или подписки. Добавьте его, когда будете готовы.', ko: '트립 패스나 구독 없이 Natio를 둘러보고 계십니다. 준비되면 언제든 추가하세요.' },
  'Add a plan': { es: 'Añadir un plan', fr: 'Ajouter un forfait', pt: 'Adicionar um plano', de: 'Tarif hinzufügen', ja: 'プランを追加', zh: '添加套餐', ar: 'إضافة خطة', hi: 'योजना जोड़ें', it: 'Aggiungi piano', ru: 'Добавить тариф', ko: '요금제 추가' },
  "Share a photo from your trip and it'll show up here.": { es: 'Comparte una foto de tu viaje y aparecerá aquí.', fr: 'Partagez une photo de votre voyage et elle apparaîtra ici.', pt: 'Compartilhe uma foto da sua viagem e ela aparecerá aqui.', de: 'Teile ein Foto von deiner Reise, und es erscheint hier.', ja: '旅行の写真を共有すると、ここに表示されます。', zh: '分享一张旅行照片，它将显示在此处。', ar: 'شارك صورة من رحلتك وستظهر هنا.', hi: 'अपनी यात्रा की फ़ोटो साझा करें और यह यहां दिखाई देगी।', it: 'Condividi una foto del tuo viaggio e apparirà qui.', ru: 'Поделитесь фото из поездки — оно появится здесь.', ko: '여행 사진을 공유하면 여기에 표시됩니다.' },
  'Billed {cadence}. Unlimited trips.': { es: 'Facturado {cadence}. Viajes ilimitados.', fr: 'Facturé {cadence}. Voyages illimités.', pt: 'Cobrado {cadence}. Viagens ilimitadas.', de: '{cadence} abgerechnet. Unbegrenzte Reisen.', ja: '{cadence}請求。無制限の旅行。', zh: '按{cadence}计费。无限次旅行。', ar: 'يُفوتر {cadence}. رحلات غير محدودة.', hi: '{cadence} बिल किया गया। असीमित यात्राएं।', it: 'Fatturato {cadence}. Viaggi illimitati.', ru: 'Оплата: {cadence}. Неограниченные поездки.', ko: '{cadence} 청구. 무제한 여행.' },
  yearly: { es: 'anualmente', fr: 'annuellement', pt: 'anualmente', de: 'jährlich', ja: '年払い', zh: '按年', ar: 'سنويًا', hi: 'वार्षिक', it: 'annualmente', ru: 'ежегодно', ko: '연간' },
  monthly: { es: 'mensualmente', fr: 'mensuellement', pt: 'mensalmente', de: 'monatlich', ja: '月払い', zh: '按月', ar: 'شهريًا', hi: 'मासिक', it: 'mensilmente', ru: 'ежемесячно', ko: '월간' },
  '{n} day left on this pass.': { es: 'Queda {n} día en este pase.', fr: "Il reste {n} jour sur ce pass.", pt: 'Resta {n} dia neste passe.', de: 'Noch {n} Tag für diesen Pass.', ja: 'このパスの残り{n}日。', zh: '此通行证还剩{n}天。', ar: 'باقي {n} يوم على هذه التذكرة.', hi: 'इस पास में {n} दिन शेष है।', it: 'Rimane {n} giorno su questo pass.', ru: 'До окончания пропуска: {n} день.', ko: '이 패스에 {n}일 남음.' },
  '{n} days left on this pass.': { es: 'Quedan {n} días en este pase.', fr: 'Il reste {n} jours sur ce pass.', pt: 'Restam {n} dias neste passe.', de: 'Noch {n} Tage für diesen Pass.', ja: 'このパスの残り{n}日。', zh: '此通行证还剩{n}天。', ar: 'باقي {n} أيام على هذه التذكرة.', hi: 'इस पास में {n} दिन शेष हैं।', it: 'Rimangono {n} giorni su questo pass.', ru: 'До окончания пропуска: {n} дней.', ko: '이 패스에 {n}일 남음.' },
  'Your trip runs longer than 14 days. This pass covers only the first 14, from {date}.': { es: 'Tu viaje dura más de 14 días. Este pase solo cubre los primeros 14, desde {date}.', fr: 'Votre voyage dure plus de 14 jours. Ce pass ne couvre que les 14 premiers, à partir du {date}.', pt: 'Sua viagem dura mais de 14 dias. Este passe cobre apenas os primeiros 14, a partir de {date}.', de: 'Deine Reise dauert länger als 14 Tage. Dieser Pass deckt nur die ersten 14 ab, ab {date}.', ja: '旅行が14日を超えています。このパスは{date}から最初の14日間のみをカバーします。', zh: '您的旅程超过14天，此通行证仅覆盖从{date}起的前14天。', ar: 'تستمر رحلتك لأكثر من 14 يومًا. تغطي هذه التذكرة أول 14 يومًا فقط، ابتداءً من {date}.', hi: 'आपकी यात्रा 14 दिनों से अधिक है। यह पास केवल {date} से पहले 14 दिनों को कवर करता है।', it: 'Il tuo viaggio dura più di 14 giorni. Questo pass copre solo i primi 14, a partire dal {date}.', ru: 'Ваша поездка длится более 14 дней. Этот пропуск покрывает только первые 14 дней, начиная с {date}.', ko: '여행 기간이 14일을 초과합니다. 이 패스는 {date}부터 첫 14일만 적용됩니다.' },

  // --- timeAgo units --------------------------------------------------
  now: { es: 'ahora', fr: "à l'instant", pt: 'agora', de: 'jetzt', ja: 'たった今', zh: '刚刚', ar: 'الآن', hi: 'अभी', it: 'ora', ru: 'сейчас', ko: '지금' },
  '{n}m': { es: '{n} min', fr: '{n} min', pt: '{n} min', de: '{n} Min.', ja: '{n}分', zh: '{n}分钟', ar: '{n} د', hi: '{n} मि', it: '{n} min', ru: '{n} мин', ko: '{n}분' },
  '{n}h': { es: '{n} h', fr: '{n} h', pt: '{n} h', de: '{n} Std.', ja: '{n}時間', zh: '{n}小时', ar: '{n} س', hi: '{n} घं', it: '{n} h', ru: '{n} ч', ko: '{n}시간' },
  '{n}d': { es: '{n} d', fr: '{n} j', pt: '{n} d', de: '{n} T.', ja: '{n}日', zh: '{n}天', ar: '{n} يوم', hi: '{n} दि', it: '{n} g', ru: '{n} дн', ko: '{n}일' },
}

function interpolate(template, params) {
  if (!params) return template
  return template.replace(/\{(\w+)\}/g, (_, key) => (params[key] ?? ''))
}

export function translate(text, language, params) {
  const template = !language || language === 'en' ? text : (dict[text]?.[language] ?? text)
  return interpolate(template, params)
}

export function useT() {
  const language = useStore((s) => s.currentUser?.language)
  return (text, params) => translate(text, language, params)
}

// Shared by NotificationsScreen and NotificationToasts so both describe a
// notification identically (and both get translated identically).
export function describeNotification(t, notif, actorName) {
  if (notif.type === 'post_like') return t('{name} liked your post', { name: actorName })
  if (notif.type === 'swipe_like') return t('{name} swiped right on you', { name: actorName })
  if (notif.type === 'message') {
    return t('{name}: {preview}', { name: actorName, preview: notif.preview || t('sent you a message') })
  }
  return ''
}

// Shared by MessagesScreen, NotificationsScreen, and PostDetail.
export function useTimeAgo() {
  const t = useT()
  return (iso) => {
    if (!iso) return ''
    const diff = Date.now() - new Date(iso).getTime()
    const mins = Math.floor(diff / 60000)
    if (mins < 1) return t('now')
    if (mins < 60) return t('{n}m', { n: mins })
    const hrs = Math.floor(mins / 60)
    if (hrs < 24) return t('{n}h', { n: hrs })
    return t('{n}d', { n: Math.floor(hrs / 24) })
  }
}
