import { countryCodes } from './countryCodes'

export const countries = countryCodes.map((c) => c.name)

export const travelers = [
  {
    id: 't1',
    name: 'Priya',
    age: 27,
    country: 'India',
    city: 'Lisbon',
    photo: 'https://i.pravatar.cc/480?img=47',
    bio: 'Second week in Lisbon, looking for someone to explore Alfama with.',
    distanceKm: 2,
  },
  {
    id: 't2',
    name: 'Mateus',
    age: 31,
    country: 'Brazil',
    city: 'Lisbon',
    photo: 'https://i.pravatar.cc/480?img=13',
    bio: 'Surfer, here for a month. Down for football and pastel de nata runs.',
    distanceKm: 5,
  },
  {
    id: 't3',
    name: 'Freya',
    age: 24,
    country: 'Norway',
    city: 'Lisbon',
    photo: 'https://i.pravatar.cc/480?img=32',
    bio: 'Just landed. Coffee first, adventure second.',
    distanceKm: 1,
  },
  {
    id: 't4',
    name: 'Kenji',
    age: 29,
    country: 'Japan',
    city: 'Lisbon',
    photo: 'https://i.pravatar.cc/480?img=51',
    bio: 'Photographer on a career break. Always chasing the golden hour.',
    distanceKm: 4,
  },
  {
    id: 't5',
    name: 'Aroha',
    age: 26,
    country: 'New Zealand',
    city: 'Lisbon',
    photo: 'https://i.pravatar.cc/480?img=25',
    bio: 'Two months into a career break. Always up for hiking or wine.',
    distanceKm: 3,
  },
  {
    id: 't6',
    name: 'Diego',
    age: 33,
    country: 'Mexico',
    city: 'Lisbon',
    photo: 'https://i.pravatar.cc/480?img=59',
    bio: 'Remote work, based here for the quarter. Know a good taco spot? Tell me.',
    distanceKm: 6,
  },
]

function daysFromNow(offset) {
  const d = new Date()
  d.setDate(d.getDate() + offset)
  return d.toISOString().slice(0, 10)
}

export const existingUsers = [
  {
    id: 'u-maria',
    email: 'maria@example.com',
    password: 'password123',
    name: 'Maria Costa',
    username: 'maria.costa',
    age: 29,
    country: 'Portugal',
    city: 'Berlin',
    photo: 'https://i.pravatar.cc/480?img=44',
    bio: 'Founder on a working trip. Coffee, co-working, and Saturday markets.',
    verified: true,
    plan: 'subscription',
    billing: 'annual',
    tripStart: daysFromNow(-20),
    tripEnd: daysFromNow(15),
  },
  {
    id: 'u-james',
    email: 'james@example.com',
    password: 'password123',
    name: 'James Whitfield',
    username: 'jwhitfield',
    age: 35,
    country: 'United Kingdom',
    city: 'Bangkok',
    photo: 'https://i.pravatar.cc/480?img=68',
    bio: 'Two weeks in Bangkok. Street food and rooftop bars.',
    verified: true,
    plan: 'trip',
    billing: null,
    tripStart: daysFromNow(-20),
    tripEnd: daysFromNow(-6),
  },
  {
    id: 'u-elena',
    email: 'elena@example.com',
    password: 'password123',
    name: 'Elena Popescu',
    username: 'elena.popescu',
    age: 32,
    country: 'Romania',
    city: 'Chiang Mai',
    photo: 'https://i.pravatar.cc/480?img=48',
    bio: 'Six weeks in Chiang Mai for a change of scenery. Coworking by day.',
    verified: true,
    plan: 'trip',
    billing: null,
    tripStart: daysFromNow(-20),
    tripEnd: daysFromNow(10),
  },
]

export const initialGroups = [
  {
    id: 'g1',
    name: 'Aussies in Lisbon',
    nationality: 'Australia',
    city: 'Lisbon',
    date: daysFromNow(-3),
    description: 'Casual meetup for Aussies passing through. Drinks at a miradouro, then wherever the night goes.',
    ownerId: 'u-maria',
    members: ['u-maria', 't3'],
    pendingRequests: ['t5'],
    ratings: [],
  },
  {
    id: 'g2',
    name: 'Brazil Crew Lisbon',
    nationality: 'Brazil',
    city: 'Lisbon',
    date: '2026-09-10',
    description: 'Futevolei on the river, then churrasco. Bring your own chair.',
    ownerId: 't2',
    members: ['t2', 't6'],
    pendingRequests: [],
    ratings: [],
  },
  {
    id: 'g3',
    name: 'Japan House Lisbon',
    nationality: 'Japan',
    city: 'Lisbon',
    date: '2026-09-18',
    description: 'Photo walk through Alfama at golden hour, ramen after.',
    ownerId: 't4',
    members: ['t4'],
    pendingRequests: [],
    ratings: [],
  },
]

export const initialPosts = [
  {
    id: 'post-1',
    authorId: 't3',
    photo: 'https://picsum.photos/seed/natio-post-freya-1/700/700',
    caption: 'First morning in Lisbon. Coffee at Miradouro was worth the climb.',
    likedBy: ['t1', 'u-maria'],
    comments: [
      { id: 'c1', authorId: 't1', text: 'That view is unreal.', at: daysFromNow(-6) },
      { id: 'c2', authorId: 't5', text: 'Which miradouro was this?', at: daysFromNow(-6) },
    ],
    at: daysFromNow(-6),
  },
  {
    id: 'post-2',
    authorId: 't3',
    photo: 'https://picsum.photos/seed/natio-post-freya-2/700/700',
    caption: 'Alfama at golden hour with the group from the meetup.',
    likedBy: ['t4'],
    comments: [{ id: 'c3', authorId: 't4', text: 'Great light in this one.', at: daysFromNow(-3) }],
    at: daysFromNow(-3),
  },
  {
    id: 'post-3',
    authorId: 't2',
    photo: 'https://picsum.photos/seed/natio-post-mateus-1/700/700',
    caption: 'Futevolei on the river. My legs are done for.',
    likedBy: ['t6', 't3'],
    comments: [{ id: 'c4', authorId: 't6', text: 'Rematch next week.', at: daysFromNow(-4) }],
    at: daysFromNow(-4),
  },
  {
    id: 'post-4',
    authorId: 't4',
    photo: 'https://picsum.photos/seed/natio-post-kenji-1/700/700',
    caption: 'Chasing the golden hour through Alfama.',
    likedBy: ['t3', 't1', 't5'],
    comments: [],
    at: daysFromNow(-8),
  },
  {
    id: 'post-5',
    authorId: 't1',
    photo: 'https://picsum.photos/seed/natio-post-priya-1/700/700',
    caption: 'Second week here and still finding new streets in Alfama.',
    likedBy: [],
    comments: [],
    at: daysFromNow(-2),
  },
  {
    id: 'post-6',
    authorId: 'u-maria',
    photo: 'https://picsum.photos/seed/natio-post-maria-1/700/700',
    caption: 'Saturday market run before a full day of calls.',
    likedBy: ['t3', 'u-james'],
    comments: [{ id: 'c5', authorId: 't3', text: 'That bread stall is the best one.', at: daysFromNow(-5) }],
    at: daysFromNow(-5),
  },
  {
    id: 'post-7',
    authorId: 'u-elena',
    photo: 'https://picsum.photos/seed/natio-post-elena-1/700/700',
    caption: 'Six weeks in and I still cowork from this same balcony every morning.',
    likedBy: ['u-maria'],
    comments: [],
    at: daysFromNow(-9),
  },
]

export const initialThreads = {
  'match-t3': {
    id: 'match-t3',
    type: 'match',
    name: 'Freya',
    photo: 'https://i.pravatar.cc/480?img=32',
    messages: [
      { id: 'm1', from: 't3', text: "Hey! Saw we're both around this week.", at: '2026-08-29T09:12:00' },
      { id: 'm2', from: 'me', text: 'Yes! Down for coffee tomorrow?', at: '2026-08-29T09:20:00' },
    ],
  },
}
